services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        UID: ${UID:-1000}
    volumes:
      - ./public:/var/www/html
    networks:
      - app_network
    depends_on:
      postgres:
        condition: service_started
      redis:
        condition: service_started
    hostname: php-fpm

  apache:
    image: httpd:2.4
    ports:
      - "8080:8080"
    volumes:
      - ./public:/var/www/html
      - ./docker/apache/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro
    networks:
      - app_network
    depends_on:
      - php
    hostname: apache

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: password
      POSTGRES_DB: symfony
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
    hostname: db

  mailhog:
    image: mailhog/mailhog
    networks:
      - app_network
    hostname: mailhog
    environment:
      MH_UI_WEB_PATH: mailhog

  adminer:
    image: adminer
    networks:
      - app_network
    hostname: adminer
    environment:
      ADMINER_DEFAULT_SERVER: db

  rabbitmq:
    image: rabbitmq:4.1.1-management-alpine
    networks:
      - app_network
    hostname: rabbitmq
    volumes:
      - ./docker/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  redis:
    image: redis:7-alpine
    networks:
      - app_network
    hostname: redis
    volumes:
      - redis_data:/data
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]

networks:
  app_network:
    ipam:
      config:
        - subnet: 172.255.0.0/24
          gateway: 172.255.0.1

volumes:
  postgres_data:
  redis_data:
