services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args: 
        UID: ${UID}
    volumes:
      - ./public:/var/www/html
    networks:
      - app_network
    depends_on:
      - postgres
    hostname: php-fpm

  apache:
    image: httpd:2.4
    volumes:
      - ./public:/var/www/html
      - ./docker/apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
    networks:
      - app_network
      - nginx-apache-reverse
    depends_on:
      - php
    hostname: local.moodjournal.com

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: password
      POSTGRES_DB: symfony
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
    hostname: db

  mailhog:
    image: mailhog/mailhog
    networks:
      - app_network
    hostname: mailhog
    environment:
      MH_UI_WEB_PATH: mailhog

networks:
  app_network:
    ipam:
      config:
        - subnet: 172.255.0.0/24
          ip_range: 172.255.0.0/24
          gateway: 172.255.0.1
  nginx-apache-reverse:
    external: true

volumes:
  postgres_data:
